name: CI/CD Pipeline

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

env:
  APP_NAME: spring-app
  PROD_SERVER: ${{ secrets.PROD_SERVER }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'  

      - name: Cache Maven dependencies
        uses: actions/cache@v3  
        with:
          path: ~/.m2  
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.7  
        with:
          host: ${{ env.PROD_SERVER }}
          username: deploy-user
          key: ${{ secrets.SSH_KEY }}
          source: "target/*.jar,docker-compose.yml,Dockerfile"
          target: /opt/path
          strip_components: 0  

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0  
        with:
          host: ${{ env.PROD_SERVER }}
          username: deploy-user
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/path
            docker-compose down || true
            docker-compose pull
            docker-compose up --build -d
            docker image prune -f  # Ajout de -f pour forcer
            docker ps